// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Address
    {
        public int AddressId { get; set; }
        public int MemberId { get; set; }
        public bool? Gender { get; set; }
        public string DestinationName { get; set; }
        public string Destination { get; set; }
        public string DestinationThe { get; set; }
        public bool? Preset { get; set; }
        public string DestinationCategory { get; set; }

        public virtual Member Member { get; set; }
    }
}