// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Cart
    {
        public int SpecId { get; set; }
        public int MemberId { get; set; }
        public int Quantity { get; set; }

        public virtual Member Member { get; set; }
        public virtual Spec Spec { get; set; }
    }
}