// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class CommonQuestion
    {
        public int CommonQuestionId { get; set; }
        public int QcategoryId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public int SatisfactionYes { get; set; }
        public int SatisfactionNo { get; set; }

        public virtual QuestionCategory Qcategory { get; set; }
    }
}