// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class CustomerQuestion
    {
        public int CustomerQuestionId { get; set; }
        public int? MemberId { get; set; }
        public int QcategoryId { get; set; }
        public string Title { get; set; }
        public string ProblemDescription { get; set; }
        public string FilePath { get; set; }
        public DateTime AskTime { get; set; }
        public string SolutionDescription { get; set; }
        public DateTime? SolveTime { get; set; }
        public int? EmployeeId { get; set; }

        public virtual Member Member { get; set; }
        public virtual QuestionCategory Qcategory { get; set; }
    }
}