// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class EassyFollow
    {
        public int MemberId { get; set; }
        public int EassyId { get; set; }
        public DateTime Ftime { get; set; }

        public virtual Essay Eassy { get; set; }
        public virtual Member Member { get; set; }
    }
}