// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Elike
    {
        public int MemberId { get; set; }
        public int EssayId { get; set; }

        public virtual Essay Essay { get; set; }
    }
}