// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Employee
    {
        public Employee()
        {
            Essays = new HashSet<Essay>();
            HSourceDetails = new HashSet<HSourceDetail>();
            Orders = new HashSet<Order>();
        }

        public int EmployeeId { get; set; }
        public string Account { get; set; }
        public string Title { get; set; }
        public int? PermissionId { get; set; }
        public string EncryptedPassword { get; set; }

        public virtual PermissionsE Permission { get; set; }
        public virtual ICollection<Essay> Essays { get; set; }
        public virtual ICollection<HSourceDetail> HSourceDetails { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}