// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class HActivity
    {
        public HActivity()
        {
            HCheckIns = new HashSet<HCheckIn>();
            HSourceDetails = new HashSet<HSourceDetail>();
        }

        public int HActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityDescribe { get; set; }
        public int HValue { get; set; }

        public virtual ICollection<HCheckIn> HCheckIns { get; set; }
        public virtual ICollection<HSourceDetail> HSourceDetails { get; set; }
    }
}