// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class HCheckIn
    {
        public int CheckInHId { get; set; }
        public int MemberId { get; set; }
        public int ActivityId { get; set; }
        public int CheckInTimes { get; set; }
        public DateTime LastTime { get; set; }

        public virtual HActivity Activity { get; set; }
        public virtual Member Member { get; set; }
    }
}