// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class HSourceDetail
    {
        public int SourceHId { get; set; }
        public int MemberId { get; set; }
        public int ActivityId { get; set; }
        public int DifferenceH { get; set; }
        public DateTime EventTime { get; set; }
        public int? TotalHSoFar { get; set; }
        public string Remark { get; set; }
        public int? EmployeeId { get; set; }

        public virtual HActivity Activity { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
    }
}