// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class News
    {
        public int NewsId { get; set; }
        public string Ntitle { get; set; }
        public DateTime Ntime { get; set; }
        public string Ncontent { get; set; }
        public int NproductId { get; set; }
        public int PhotoId { get; set; }
        public int TagId { get; set; }
    }
}