// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class OrderStatusDescription
    {
        public OrderStatusDescription()
        {
            Orders = new HashSet<Order>();
        }

        public int DescriptionId { get; set; }
        public int? StatusId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}