// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
            ProductComments = new HashSet<ProductComment>();
        }

        public int OrderId { get; set; }
        public int MemberId { get; set; }
        public int? EmployeeId { get; set; }
        public int Total { get; set; }
        public string Payment { get; set; }
        public DateTime? ShippedDate { get; set; }
        public string ShipVia { get; set; }
        public int Freight { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipPhone { get; set; }
        public DateTime? RequestRefundTime { get; set; }
        public bool RequestRefund { get; set; }
        public DateTime CreatedTime { get; set; }
        public int StatusId { get; set; }
        public int? StatusDescriptionId { get; set; }
        public int? Discount { get; set; }
        public string PayInfo { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        public virtual OrderStatus Status { get; set; }
        public virtual OrderStatusDescription StatusDescription { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ProductComment> ProductComments { get; set; }
    }
}