// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class PermissionsE
    {
        public PermissionsE()
        {
            Employees = new HashSet<Employee>();
        }

        public int PermissionMId { get; set; }
        public string Level { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}