// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class PermissionsM
    {
        public PermissionsM()
        {
            Members = new HashSet<Member>();
        }

        public int PermissionId { get; set; }
        public string Level { get; set; }

        public virtual ICollection<Member> Members { get; set; }
    }
}