// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class ProductComment
    {
        public ProductComment()
        {
            PcommentImgs = new HashSet<Image>();
        }

        public int CommentId { get; set; }
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public string CommentContent { get; set; }
        public int Score { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }

        public virtual ICollection<Image> PcommentImgs { get; set; }
    }
}