// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class QuestionCategory
    {
        public QuestionCategory()
        {
            CommonQuestions = new HashSet<CommonQuestion>();
            CustomerQuestions = new HashSet<CustomerQuestion>();
        }

        public int QcategoryId { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<CommonQuestion> CommonQuestions { get; set; }
        public virtual ICollection<CustomerQuestion> CustomerQuestions { get; set; }
    }
}