// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Tag
    {
        public Tag()
        {
            Essays = new HashSet<Essay>();
            Products = new HashSet<Product>();
            Videos = new HashSet<Video>();
        }

        public int Id { get; set; }
        public string TagName { get; set; }

        public virtual ICollection<Essay> Essays { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}