// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class VcommentLike
    {
        public int MemberId { get; set; }
        public int CommentId { get; set; }

        public virtual VideoComment Comment { get; set; }
    }
}