// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class VideoCategory
    {
        public VideoCategory()
        {
            Essays = new HashSet<Essay>();
            Videos = new HashSet<Video>();
        }

        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }

        public virtual ICollection<Essay> Essays { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}