// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class VideoComment
    {
        public VideoComment()
        {
            VcommentLikes = new HashSet<VcommentLike>();
        }

        public int Id { get; set; }
        public int VideoId { get; set; }
        public int MemberId { get; set; }
        public string Comment { get; set; }
        public DateTime CreatedTime { get; set; }
        public int Like { get; set; }

        public virtual Member Member { get; set; }
        public virtual Video Video { get; set; }
        public virtual ICollection<VcommentLike> VcommentLikes { get; set; }
    }
}