// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class Video
    {
        public Video()
        {
            VideoComments = new HashSet<VideoComment>();
            VideoLikes = new HashSet<VideoLike>();
            Tags = new HashSet<Tag>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public int CategoryId { get; set; }
        public int ImageId { get; set; }
        public DateTime? OnShelffTime { get; set; }
        public DateTime? OffShelffTime { get; set; }
        public bool? IsOnShelff { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual VideoCategory Category { get; set; }
        public virtual Image Image { get; set; }
        public virtual VideoView VideoView { get; set; }
        public virtual ICollection<VideoComment> VideoComments { get; set; }
        public virtual ICollection<VideoLike> VideoLikes { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
    }
}