// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HStyleApi.Models.EFModels
{
    public partial class VideoLike
    {
        public int VideoId { get; set; }
        public int MemberId { get; set; }

        public virtual Video Video { get; set; }
    }
}